### PR TITLE
Wizard for new AWS Account

### PR DESCRIPTION
**Pull request by hug33k**
I added a Wizard to help users to add easily an AWS Account to Trackit, with screenshots to explain them how to do it.

capture d ecran 2018-01-09 a 15 19 32
capture d ecran 2018-01-09 a 15 19 41
capture d ecran 2018-01-09 a 15 19 56
capture d ecran 2018-01-09 a 15 20 11

N.B. :
- [x] Screenshots needs to be added in Wizard
- [x] Unit testing

### CODE REVIEW

**Comment by alexis-ld** [comment]
@hug33k : I'll wait for the screenshots to be added before considering merging. Please add those :) .
Try to be as didactic as possible, think of it as a step by step tutorial. We need text explaining the user what to do along with the screenshots.

If the space becomes an issue for the screenshots (because of the size of the modal) you might just highlight the related words in the help text and display the screenshots in a popover on those words.

For example : "[...] then **copy the role ARN from the AWS console** " when hoverting those words you could display a screenshot of AWS console cropped to where the ARN is.

Does that make sense ?

**Comment by hug33k** [comment]
@alexis-ld : I updated screenshots in PR description.
You will be able to click on screenshots in Wizard, to see the picture in a bigger modal.

**Comment by alexis-ld** [comment]
@hug33k  : The screenshots seems a bit too big (the first step for example is way too vertical). Also we should add a bit more margin on the thumbnails.

Two solutions : 

* Do the words hovering thing I described above
* Display the screenshots in smaller thumbnails to encourage the user to click to see the big picture

**Comment by alexis-ld** [comment]
@hug33k : Also tests are failing

**Comment by hug33k** [comment]
@alexis-ld :
- Screenshots : Is it good this way ?
capture d ecran 2018-01-09 a 15 41 50
capture d ecran 2018-01-09 a 15 41 58

- Tests : Working on it.

**Comment by alexis-ld** [comment]
@hug33k  : Better but not totally right. 
We need more margins around the screenshot, the text is too close. 
Also the screenshots are not centered properly.
It seems it's taking a lot of space. Maybe changing the text to (Click here for a screenshot) and just removing it would be a better option.

Can you also complete the small infos popover in the fields adding more infos ?
For example for the Role Arn you could add things like : "This value should be retrieved in you AWS console. See step X for more details" .

**Comment by hug33k** [comment]
@alexis-ld :
- Screenshot preview have been removed and replaced by `( Click here to see screenshot )`
- Steps numbers have beed added inside popovers
capture d ecran 2018-01-09 a 17 22 36

**Comment by alexis-ld** [comment]
@hug33k  :  Couple changes : 

1. The "Click here to select screenshot". 
-Please make it blue like we decided.
-The cursor of the user is not a pointer when hovered, so it's not obvious we can click on it. Please add this.

screen shot 2018-01-15 at 11 00 29

2. When a screenshot is open, it's not clear how to close it. There is no "close" button clicking on the grey overlay on background doesn't close it (it seems to close it we need to click on the white border around it which is not a good UX at all). Can you add a close button or a cross at the top right or something similar ?

screen shot 2018-01-15 at 11 01 17

3. The font of the bottom stepper is a bit small.

screen shot 2018-01-15 at 11 01 53

4. Couple typos and reformulations : 
Step 1 Point 5 : Follow this screenshot to configure your new role correctly,
(based on information available -> using the informations provided) (bellow -> below)
Step 2 Point 2 : Fill the form (bellow -> below) with ...
Step 3 : Fill the form with the location of a S3 (buckets->bucket) that contains bills

5. Is it possible to have a "Previous" button next to the "Next" button ?

**Comment by hug33k** [comment]
@alexis-ld :
1., 2., 3. & 4. are now fixed.

5. I can add a "Previous" button in Step 2 to let user go back to Step 1. But if I add this button in Step 3, user will have a new form to create an account, since request for account creation is triggered when user go from Step 2 to Step 3.

**Pull request merged**
